import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Yuri's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-glass-effect bg-cityBg bg-top bg-no-repeat">
        <div className="flex h-screen w-screen items-center justify-center overflow-x-hidden">
          <main className="mx-3 mt-16 grid w-full max-w-[50rem] grid-cols-2 items-center justify-center gap-3">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
